### ISSUE TITLE
Refactor golangci-lint configuration file

### ISSUE THREAD

**Issue by alexandear** [go-critic/go-critic#1460]
It's strange that the repo contains [`.golangci.yml`](https://github.com/go-critic/go-critic/blob/4affbc69a977779c40cb0ef0410cbf2558527f49/.golangci.yml#L1) file with JSON content. I propose renaming the file to `.golangci.json` or changing the content to YAML.

Good first issue.

<details><summary>.golangci.yml</summary>
<p>

```yaml
run:
  timeout: "3m"

linters:
  fast: false
  enable:
    - errcheck
    - gosec
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  disable:
    - depguard
    - dupl
    - gocyclo
    - lll
    - prealloc

linters-settings:
  gocritic:
    enabled-checks:
      - ruleguard
    settings:
      ruleguard:
        rules: "rules.go"
  gosec:
    excludes: ["G115"]

issues:
  exclude-dirs: ["checkers/rules"]
```

</p>
</details>
